version: "3.9"

services:
  hygge:
    build: . 
    ports:
      - "1212:8080"
    environment:
      API_KEY: ${API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_URL: ${S3_URL}
